itsparth20/Data-structure-and-Algorithms

LeetCode/LicenseKeyFormatting.java

https://leetcode.com/problems/license-key-formatting/
Example 1:
Input: S = "2-4A0r7-4k", K = 4
Output: "24A0-R74K"
Explanation: The string S has been split into two parts, each part has 4
characters.
Example 2:
Input: S = "2-4A0r7-4k", K = 3
Output: "24-A0R-74K"
Explanation: The string S has been split into three parts, each part has
3 characters except the first part as it could be shorter as said above.
Note:
The length of string S will not exceed 12,000, and K is a positive
integer.
String S consists only of alphanumerical characters (a-z and/or A-Z
and/or 0-9) and dashes(-).
String S is non-empty.

License Key Formatting

---

LeetCode/IntegertoRoman.java

https://leetcode.com/problems/integer-to-roman/#/description

12. Integer to Roman

---

LeetCode/MinStack/MinStack.java

Design a stack that supports push, pop, top, and retrieving the
minimum element in constant time.
push(x) -- Push element x onto stack.
pop() -- Removes the element on top of the stack.
top() -- Get the top element.
getMin() -- Retrieve the minimum element in the stack.
Example:
MinStack minStack = new MinStack();
minStack.push(-2);
minStack.push(0);
minStack.push(-3);
minStack.getMin();   --> Returns -3.
minStack.pop();
minStack.top();      --> Returns 0.
minStack.getMin();   --> Returns -2.

155. Min Stack

---

LeetCode/IntersectionofTwoLinkedList/ListNode.java
LeetCode/IntersectionofTwoLinkedList/Solution.java

https://leetcode.com/problems/intersection-of-two-linked-lists/description/
Write a program to find the node at which the intersection of two singly linked lists begins.
For example, the following two linked lists:
A:          a1 → a2
↘
c1 → c2 → c3
↗
B:     b1 → b2 → b3
begin to intersect at node c1.
Notes:
If the two linked lists have no intersection at all, return null.
The linked lists must retain their original structure after the function returns.
You may assume there are no cycles anywhere in the entire linked structure.
Your code should preferably run in O(n) time and use only O(1) memory.

160. Intersection of Two Linked Lists

---

LeetCode/majorityelement/MajorityElement.java

Given an array of size n, find the majority element. The majority element
is the element that appears more than ⌊ n/2 ⌋ times.
You may assume that the array is non-empty and the majority element
always exist in the array.

169. Majority Element

---

LeetCode/excelsheetcolumnnumber/ExcelSheetColumnNumber.java

https://leetcode.com/problems/excel-sheet-column-number/description/
Given a column title as appear in an Excel sheet, return its
corresponding column number.
For example:
A -> 1
B -> 2
C -> 3
...
Z -> 26
AA -> 27
AB -> 28

171. Excel Sheet Column Number

---

LeetCode/factorialtrailingzeroes/FactorialTrailingZeroes.java

https://leetcode.com/problems/factorial-trailing-zeroes/description/
Given an integer n, return the number of trailing zeroes in n!.
Note: Your solution should be in logarithmic time complexity.

172. Factorial Trailing Zeroes

---

LeetCode/largestnumber/LargestNumber.java
LeetCode/rotatearray/RotateArray.java

https://leetcode.com/problems/largest-number/description/
Given a list of non negative integers, arrange them such that they form the largest number.
For example, given [3, 30, 34, 5, 9], the largest formed number is 9534330.
Note: The result may be very large, so you need to return a string instead of an integer.

179. Largest Number

---

CodingChallenge/FindSortestPath/DLPriorityQueue.java
CodingChallenge/FindSortestPath/FindShortestPath.java
CodingChallenge/FindSortestPath/PriorityNode.java
LeetCode/arraynesting/ArrayNesting.java

A zero-indexed array A of length N contains all integers from 0 to N-1. Find and return
the longest length of set S, where S[i] = {A[i], A[A[i]], A[A[A[i]]], ... } subjected to
the rule below.
Suppose the first element in S starts with the selection of element A[i] of index = i,
the next element in S should be A[A[i]], and then A[A[A[i]]]… By that analogy, we stop
adding right before a duplicate element occurs in S.
Example 1:
Input: A = [5,4,0,3,1,6,2]
Output: 4
Explanation:
A[0] = 5, A[1] = 4, A[2] = 0, A[3] = 3, A[4] = 1, A[5] = 6, A[6] = 2.
One of the longest S[K]:
S[0] = {A[0], A[5], A[6], A[2]} = {5, 6, 2, 0}

565. Array Nesting

---

LeetCode/courseschedule/CourseSchedule.java

https://leetcode.com/problems/course-schedule/description/
There are a total of n courses you have to take, labeled from 0 to n - 1.
Some courses may have prerequisites, for example to take course 0 you have to first take course 1, which is expressed as a pair: [0,1]
Given the total number of courses and a list of prerequisite pairs, is it possible for you to finish all courses?
For example:
2, [[1,0]]
There are a total of 2 courses to take. To take course 1 you should have finished course 0. So it is possible.
2, [[1,0],[0,1]]
There are a total of 2 courses to take. To take course 1 you should have finished course 0, and to take course 0 you should also have finished course 1. So it is impossible.

207. Course Schedule

---

LeetCode/courseschedule2/CourseSchedule2.java

https://leetcode.com/problems/course-schedule-ii/description/
There are a total of n courses you have to take, labeled from 0 to n-1.
Some courses may have prerequisites, for example to take course 0 you
have to first take course 1, which is expressed as a pair: [0,1]
Given the total number of courses and a list of prerequisite pairs,
return the ordering of courses you should take to finish all courses.
There may be multiple correct orders, you just need to return one of
them. If it is impossible to finish all courses, return an empty array.
Example 1:
Input: 2, [[1,0]]
Output: [0,1]
Explanation: There are a total of 2 courses to take. To take course 1
you should have finished
course 0. So the correct course order is [0,1] .
Example 2:
Input: 4, [[1,0],[2,0],[3,1],[3,2]]
Output: [0,1,2,3] …

210. Course Schedule II

---

LeetCode/theskylineProblem/SkylineProblem.java

https://leetcode.com/problems/the-skyline-problem/description/
A city's skyline is the outer contour of the silhouette formed by all
the buildings in that city when viewed from a distance. Now suppose you
are given the locations and height of all the buildings as shown on a
cityscape photo (Figure A), write a program to output the skyline
formed by these buildings collectively (Figure B).
The geometric information of each building is represented by a triplet
of integers [Li, Ri, Hi], where Li and Ri are the x coordinates of the
left and right edge of the ith building, respectively, and Hi is its
height. It is guaranteed that 0 ≤ Li, Ri ≤ INT_MAX, 0 < Hi ≤ INT_MAX,
and Ri - Li > 0. You may assume all buildings are perfect rectangles
grounded on an absolutely flat surface at height 0.
For …

218. The Skyline Problem

---

LeetCode/basiccalculatorII/BasicCalculatorII.java

Implement a basic calculator to evaluate a simple expression string.
The expression string contains only non-negative integers, +, -, *, /
operators and empty spaces . The integer division should truncate toward zero.
Example 1:
Input: "3+2*2"
Output: 7
Example 2:
Input: " 3/2 "
Output: 1
Example 3:
Input: " 3+5 / 2 "
Output: 5

227. Basic Calculator II

---

LeetCode/complete-binary-tree-creation/CreateTree.java
LeetCode/complete-binary-tree-creation/TreeNode.java

If we wanna create a complete binary tree then we can create a list
of node and then pass the list to CreateTree class and that will
connect all left and right node and return the root node of tree.

Complete Binary Tree Creation - Helper

---

LeetCode/kthsmallestelement/KthSmallestElement.java

https://leetcode.com/problems/kth-smallest-element-in-a-bst/description/
Given a binary search tree, write a function kthSmallest to find the kth
smallest element in it.
Note:
You may assume k is always valid, 1 ≤ k ≤ BST's total elements.
Example 1:
Input: root = [3,1,4,null,2], k = 1
3
/ \
1   4
\
2
Output: 1
Example 2:
Input: root = [5,3,6,2,4,null,null,1], k = 3
5
/ \
3   6
/ \
2   4
/
1
Output: 3

230. Kth Smallest Element in a BST

---

LeetCode/slidingwindowmaximum/SlidingWindowMaximum.java

https://leetcode.com/problems/sliding-window-maximum/description/
Given an array nums, there is a sliding window of size k which is moving
from the very left of the array to the very right. You can only see the
k numbers in the window. Each time the sliding window moves right by one
position. Return the max sliding window.
Example:
Input: nums = [1,3,-1,-3,5,3,6,7], and k = 3
Output: [3,3,5,5,6,7]
Explanation:
Window position                Max
---------------               -----
[1  3  -1] -3  5  3  6  7       3
1 [3  -1  -3] 5  3  6  7       3
1  3 [-1  -3  5] 3  6  7       5
1  3  -1 [-3  5  3] 6  7       5
1  3  -1  -3 [5  3  6] 7       6
1  3  -1  -3  5 [3  6  7]      7
Note:
You may assume k is always valid, 1 ≤ k ≤ input array's size for non-empty array.

239. Sliding Window Maximum

---

LeetCode/searchtwodmatrixtwo/Search2DMatrix2.java

https://leetcode.com/problems/search-a-2d-matrix-ii/description/
Write an efficient algorithm that searches for a value in an m x n matrix.
This matrix has the following properties:
Integers in each row are sorted in ascending from left to right.
Integers in each column are sorted in ascending from top to bottom.
Example:
Consider the following matrix:
[
[1,   4,  7, 11, 15],
[2,   5,  8, 12, 19],
[3,   6,  9, 16, 22],
[10, 13, 14, 17, 24],
[18, 21, 23, 26, 30]
]
Given target = 5, return true.
Given target = 20, return false.

240. Search a 2D Matrix II

---

CodingChallenge/FreeLancer/arraymanipulation/Solution.java

Q: You have given the array and you have to find the number of ways you can make that
array in ascending order by removing single element from the array.
Note: Solution does not worry about time complexity. Looking for answer

Freelance - Coding help

---

LeetCode/missingnumber/MissingNumber.java

https://leetcode.com/problems/missing-number/description/
Given an array containing n distinct numbers taken from 0, 1, 2, ..., n,
find the one that is missing from the array.
Example 1:
Input: [3,0,1]
Output: 2
Example 2:
Input: [9,6,4,2,3,5,7,0,1]
Output: 8
Note:
Your algorithm should run in linear runtime complexity. Could you implement it using
only constant extra space complexity?

268. Missing Number

---

LeetCode/findtheduplicatenumber/FindtheDuplicateNumber.java

https://leetcode.com/problems/find-the-duplicate-number/description/
Given an array nums containing n + 1 integers where each integer is between 1 and n
(inclusive), prove that at least one duplicate number must exist. Assume that there
is only one duplicate number, find the duplicate one.
Example 1:
Input: [1,3,4,2,2]
Output: 2
Example 2:
Input: [3,1,3,4,2]
Output: 3
Note:
You must not modify the array (assume the array is read only).
You must use only constant, O(1) extra space.
Your runtime complexity should be less than O(n2).
There is only one duplicate number in the array, but it could be repeated more than once.

287. Find the Duplicate Number

---

LeetCode/gameoflife/GameofLife.java

https://leetcode.com/problems/game-of-life/description/
According to the Wikipedia's article: "The Game of Life, also known simply as Life,
is a cellular automaton devised by the British mathematician John Horton Conway in 1970."
Given a board with m by n cells, each cell has an initial state live (1) or dead (0).
Each cell interacts with its eight neighbors (horizontal, vertical, diagonal)
using the following four rules (taken from the above Wikipedia article):
Any live cell with fewer than two live neighbors dies, as if caused by under-population.
Any live cell with two or three live neighbors lives on to the next generation.
Any live cell with more than three live neighbors dies, as if by over-population..
Any dead cell with exactly three live neighbors becomes a live cell, as if by …

289. Game of Life

---

LeetCode/coinchange/CoinChange.java

https://leetcode.com/problems/coin-change/description/
You are given coins of different denominations and a total
amount of money amount. Write a function to compute the fewest
number of coins that you need to make up that amount. If that amount
of money cannot be made up by any combination of the coins, return -1.
Example 1:
Input: coins = [1, 2, 5], amount = 11
Output: 3
Explanation: 11 = 5 + 5 + 1
Example 2:
Input: coins = [2], amount = 3
Output: -1

322. Coin Change

---

LeetCode/countofsmallernumberafterself/CountOfSmallerNumberAfterSelf.java

https://leetcode.com/problems/coin-change/description/
You are given coins of different denominations and a total
amount of money amount. Write a function to compute the fewest
number of coins that you need to make up that amount. If that amount
of money cannot be made up by any combination of the coins, return -1.
Example 1:
Input: coins = [1, 2, 5], amount = 11
Output: 3
Explanation: 11 = 5 + 5 + 1
Example 2:
Input: coins = [2], amount = 3
Output: -1

315. Count of Smaller Numbers After Self

---

LeetCode/findmedianfromdatastream/FindMedianfromDataStream.java

https://leetcode.com/problems/find-median-from-data-stream/description/
Median is the middle value in an ordered integer list. If the size of the
list is even, there is no middle value. So the median is the mean of the two middle value.
For example,
[2,3,4], the median is 3
[2,3], the median is (2 + 3) / 2 = 2.5
Design a data structure that supports the following two operations:
void addNum(int num) - Add a integer number from the data stream to the data structure.
double findMedian() - Return the median of all elements so far.
Example:
addNum(1)
addNum(2)
findMedian() -> 1.5
addNum(3)
findMedian() -> 2

295. Find Median from Data Stream

---

LeetCode/countmaxcommoncharacter/CountMaxCommonCharacter.java

Sum the max of the occurence of the character.
s1 = "abbaccdb";
s2 = "aaaaaabbzdddddddx";
a=6
b=3
d=7
Total = 6+3+7=16

CountMaxCommonCharacter

---

LeetCode/serializeanddeserializebinarytree/Codec.java

https://leetcode.com/problems/serialize-and-deserialize-binary-tree/description/
Serialization is the process of converting a data structure or object into a sequence of
bits so that it can be stored in a file or memory buffer, or transmitted across a network
connection link to be reconstructed later in the same or another computer environment.
Design an algorithm to serialize and deserialize a binary tree. There is no restriction
on how your serialization/deserialization algorithm should work. You just need to ensure
that a binary tree can be serialized to a string and this string can be deserialized
to the original tree structure.
Example:
You may serialize the following tree:
1
/ \
2   3
/ \
4   5
as "[1,2,3,null,null,4,5]"

297. Serialize and Deserialize Binary Tree

---

LeetCode/WiggleSortII/WiggleSortII.java

https://leetcode.com/problems/wiggle-sort-ii/description/
Given an unsorted array nums, reorder it such that nums[0] < nums[1] > nums[2] < nums[3]....
Example 1:
Input: nums = [1, 5, 1, 1, 6, 4]
Output: One possible answer is [1, 4, 1, 5, 1, 6].
Example 2:
Input: nums = [1, 3, 2, 2, 3, 1]
Output: One possible answer is [2, 3, 1, 3, 1, 2].
Note:
You may assume all input has valid answer.

324. Wiggle Sort II

---

LeetCode/powerofthree/PowerofThree.java

https://leetcode.com/problems/power-of-three/description/
Given an integer, write a function to determine if it is a power of three.
Example 1:
Input: 27
Output: true
Example 2:
Input: 0
Output: false
Example 3:
Input: 9
Output: true
Example 4:
Input: 45
Output: false

326. Power of Three

---

LeetCode/oddevenlinkedlist/OddEvenLinkedList.java

https://leetcode.com/problems/odd-even-linked-list/description/
Given a singly linked list, group all odd nodes together followed by
the even nodes. Please note here we are talking about the node number
and not the value in the nodes.
You should try to do it in place. The program should run in O(1)
space complexity and O(nodes) time complexity.
Example 1:
Input: 1->2->3->4->5->NULL
Output: 1->3->5->2->4->NULL
Example 2:
Input: 2->1->3->5->6->4->7->NULL
Output: 2->3->6->7->1->5->4->NULL

328. Odd Even Linked List

---

LeetCode/longesincreasingpathinamatrix/LongestIncreasingPathinaMatrix.java

https://leetcode.com/problems/longest-increasing-path-in-a-matrix/description/
Given an integer matrix, find the length of the longest increasing path.
From each cell, you can either move to four directions: left, right, up or
down. You may NOT move diagonally or move outside of the boundary (i.e. wrap-around is not allowed).
Example 1:
Input: nums =
[
[9,9,4],
[6,6,8],
[2,1,1]
]
Output: 4
Explanation: The longest increasing path is [1, 2, 6, 9].
Example 2:
Input: nums =
[
[3,4,5],
[3,2,6],
[2,2,1]
]
Output: 4
Explanation: The longest increasing path is [3, 4, 5, 6]. Moving diagonally is not allowed.

329. Longest Increasing Path in a Matrix

---

LeetCode/increasingtripletsubsequence/IncreasingTripletSubsequence.java

https://leetcode.com/problems/increasing-triplet-subsequence/description/
Given an unsorted array return whether an increasing subsequence of length 3 exists or not in the array.
Formally the function should:
Return true if there exists i, j, k
such that arr[i] < arr[j] < arr[k] given 0 ≤ i < j < k ≤ n-1 else return false.
Note: Your algorithm should run in O(n) time complexity and O(1) space complexity.
Example 1:
Input: [1,2,3,4,5]
Output: true
Example 2:
Input: [5,4,3,2,1]
Output: false

334. Increasing Triplet Subsequence

---

LeetCode/flattennestedlistiterator/FlattenNestedListIterator.java

https://leetcode.com/problems/flatten-nested-list-iterator/description/
Given a nested list of integers, implement an iterator to flatten it.
Each element is either an integer, or a list -- whose elements may also be integers or other lists.
Example 1:
Input: [[1,1],2,[1,1]]
Output: [1,1,2,1,1]
Explanation: By calling next repeatedly until hasNext returns false,
the order of elements returned by next should be: [1,1,2,1,1].
Example 2:
Input: [1,[4,[6]]]
Output: [1,4,6]
Explanation: By calling next repeatedly until hasNext returns false,
the order of elements returned by next should be: [1,4,6].

341. Flatten Nested List Iterator

---

LeetCode/topkfrequentelements/TopKFrequentElements.java

https://leetcode.com/problems/top-k-frequent-elements/description/
Given a non-empty array of integers, return the k most frequent elements.
Example 1:
Input: nums = [1,1,1,2,2,3], k = 2
Output: [1,2]
Example 2:
Input: nums = [1], k = 1
Output: [1]
Note:
You may assume k is always valid, 1 ≤ k ≤ number of unique elements.
Your algorithm's time complexity must be better than O(n log n), where n is the array's size.

347. Top K Frequent Elements

---

LeetCode/intersectionoftwoarraystwo/Solution.java

Given two arrays, write a function to compute their intersection.
Example 1:
Input: nums1 = [1,2,2,1], nums2 = [2,2]
Output: [2,2]
Example 2:
Input: nums1 = [4,9,5], nums2 = [9,4,9,8,4]
Output: [4,9]
Note:
Each element in the result should appear as many times as it shows in both arrays.
The result can be in any order.

350. Intersection of Two Arrays II

---

LeetCode/firstuniquecharacterinastring/FirstUniqueCharacterInaString.java

Given a string, find the first non-repeating character in it and return it's
index. If it doesn't exist, return -1.
Examples:
s = "leetcode"
return 0.
s = "loveleetcode",
return 2.

387. First Unique Character in a String

---

LeetCode/fizzbuzz/FizzBuzz.java

Write a program that outputs the string representation of numbers from 1 to n.
But for multiples of three it should output “Fizz” instead of the number
and for the multiples of five output “Buzz”.
For numbers which are multiples of both three and five output “FizzBuzz”.
Example:
n = 15,
Return:
[
"1",
"2",
"Fizz",
"4",
"Buzz",
"Fizz",
"7",
"8",
"Fizz",
"Buzz",
"11",
"Fizz",
"13",
"14",
"FizzBuzz"
]

412. Fizz Buzz

---

CodingChallenge/google/internship/fruittree.java

In a grader there are N fruit trees growing in a row. Each tree produces one
Fruit of some type.
Little Amy goes to the grader to collect some fruit. She has two baskets that
Can hold any number of fruit, but she only wants to put one type of fruit in
Each basket. When Amy enters the grader, she goes to some tree,  collects
The fruit from it (every tree produces exactly one fruit) and then goes to the
Next tree to the right. Amy continues her walk until she encounters a tree with
A fruit that she cannot put in any of her baskets (each of them already has
A fruit of a different type), or when the garden ends. Amy never throws any fruit
Away from her basket.
What is the maximum number of fruit she can collect?
Write a function: that given a array A of N integers, representing consecutive …

Collect Fruit Problem

---

LeetCode/houserobber/houserobber.py

https://leetcode.com/problems/house-robber/
You are a professional robber planning to rob houses along a street.
Each house has a certain amount of money stashed, the only constraint
stopping you from robbing each of them is that adjacent houses have
security system connected and it will automatically contact the police
if two adjacent houses were broken into on the same night.
Given a list of non-negative integers representing the amount of money
of each house, determine the maximum amount of money you can rob tonight
without alerting the police.
Example 1:
Input: [1,2,3,1]
Output: 4
Explanation: Rob house 1 (money = 1) and then rob house 3 (money = 3).
Total amount you can rob = 1 + 3 = 4.
Example 2:
Input: [2,7,9,3,1]
Output: 12
Explanation: Rob house 1 (money = 2), rob house 3 (money …

198. House Robber

---

LeetCode/ContainerWithMostWater.java

https://leetcode.com/problems/container-with-most-water/
Given n non-negative integers a1, a2, ..., an ,
where each represents a point at coordinate (i, ai).
n vertical lines are drawn such that the two
endpoints of line i is at (i, ai) and (i, 0).
Find two lines, which together with x-axis forms
a container, such that the container contains the most water.
Note: You may not slant the container and n is at least 2.
Example:
Input: [1,8,6,2,5,4,8,3,7]
Output: 49

11. Container With Most Water

---

LeetCode/RemoveNthNodeFromEndofList/RemoveNthNodeFromEndofList.java

Given a linked list, remove the n-th node from the end of list
and return its head.
Example:
Given linked list: 1->2->3->4->5, and n = 2.
After removing the second node from the end, the linked list becomes 1->2->3->5.
Note:
Given n will always be valid.
https://leetcode.com/problems/remove-nth-node-from-end-of-list/

19. Remove Nth Node From End of List

---

LeetCode/SwapNodesinPairs/SwapNodesinPairs.java

https://leetcode.com/problems/swap-nodes-in-pairs/submissions/
Given a linked list, swap every two adjacent nodes and return its head.
Example:
Given 1->2->3->4, you should return the list as 2->1->4->3.
Note:
Your algorithm should use only constant extra space.
You may not modify the values in the list's nodes, only nodes itself may be changed.

24. Swap Nodes in Pairs

---

LeetCode/ReverseNodesink-Group/ReverseNodesink-Group.java

https://leetcode.com/problems/reverse-nodes-in-k-group/
Given a linked list, reverse the nodes of a linked list k at a time and
return its modified list.
k is a positive integer and is less than or equal to the length of the
linked list. If the number of nodes is not a multiple of k then left-out
nodes in the end should remain as it is.
Example:
Given this linked list: 1->2->3->4->5
For k = 2, you should return: 2->1->4->3->5
For k = 3, you should return: 3->2->1->4->5
Note:
Only constant extra memory is allowed.
You may not alter the values in the list's nodes, only nodes itself may be changed.

25. Reverse Nodes in k-Group

---

LeetCode/LengthofLastWord/LengthofLastWord.java

https://leetcode.com/problems/length-of-last-word/
Given a string s consists of upper/lower-case alphabets and empty space characters ' ', return the length of last word in the string.
If the last word does not exist, return 0.
Note: A word is defined as a character sequence consists of non-space characters only.
Example:
Input: "Hello World"
Output: 5

58. Length of Last Word

---

LeetCode/AddBinary/AddBinary.java

https://leetcode.com/problems/add-binary/
Given two binary strings, return their sum (also a binary string).
The input strings are both non-empty and contains only characters 1 or 0.
Example 1:
Input: a = "11", b = "1"
Output: "100"
Example 2:
Input: a = "1010", b = "1011"
Output: "10101"

67. Add Binary

---

LeetCode/reverse_linked_list_ll.py

Reverse a linked list from position m to n. Do it in one-pass.
Note: 1 ≤ m ≤ n ≤ length of list.
Example:
Input: 1->2->3->4->5->NULL, m = 2, n = 4
Output: 1->4->3->2->5->NULL

92. Reverse Linked List II
